(function(){
"use strict";
const KEY="nathauxfx_public_language";
const T={fr:{},es:{}};
function add(en,fr,es){T.fr[en]=fr;T.es[en]=es;}
[
["Contact","Contact","Contacto"],["Support","Assistance","Soporte"],["Login","Connexion","Iniciar sesión"],["Get Started","Commencer","Comenzar"],["About","À propos","Acerca de"],["Home","Accueil","Inicio"],["How It Works","Fonctionnement","Cómo funciona"],["Risk","Risque","Riesgo"],["Risk Disclosure","Avis de risque","Divulgación de riesgos"],["Terms","Conditions","Términos"],["Privacy","Confidentialité","Privacidad"],
["● LIVE","● EN DIRECT","● EN VIVO"],["Real-time analysis • Risk controls • Built for traders","Analyse en temps réel • Contrôles du risque • Conçu pour les traders","Análisis en tiempo real • Controles de riesgo • Creado para traders"],["Smarter Signals.","Des signaux plus intelligents.","Señales más inteligentes."],["Stronger Trades.","Des transactions plus solides.","Operaciones más sólidas."],["Explore Platform →","Explorer la plateforme →","Explorar la plataforma →"],["⚡ Real-time Alerts","⚡ Alertes en temps réel","⚡ Alertas en tiempo real"],["◎ Rule-Based Analysis","◎ Analyse fondée sur des règles","◎ Análisis basado en reglas"],["🛡 Risk Controls","🛡 Contrôles du risque","🛡 Controles de riesgo"],
["Trading software — not a broker","Un logiciel de trading — pas un courtier","Software de trading — no un bróker"],["No custody of trading funds","Aucune garde des fonds de trading","Sin custodia de fondos de trading"],["Brokerage funds remain with the user's chosen broker.","Les fonds restent auprès du courtier choisi par l’utilisateur.","Los fondos permanecen con el bróker elegido por el usuario."],["No profit guarantees","Aucune garantie de profit","Sin garantías de beneficios"],["Markets involve risk and losses are possible.","Les marchés comportent des risques et des pertes sont possibles.","Los mercados implican riesgo y pueden producirse pérdidas."],["User-controlled automation","Automatisation contrôlée par l’utilisateur","Automatización controlada por el usuario"],["Automation can be enabled or disabled by the account user.","L’utilisateur peut activer ou désactiver l’automatisation.","El usuario puede activar o desactivar la automatización."],["Transparent purpose","Objectif transparent","Propósito transparente"],["Analysis, alerts, risk tools, cTrader integration and signal sharing.","Analyse, alertes, outils de risque, intégration cTrader et partage de signaux.","Análisis, alertas, herramientas de riesgo, integración con cTrader y señales compartidas."],["Your Broker","Votre courtier","Tu bróker"],["Funds stay in your brokerage account","Les fonds restent dans votre compte de courtage","Los fondos permanecen en tu cuenta de corretaje"],["User-authorized trade execution","Exécution autorisée par l’utilisateur","Ejecución autorizada por el usuario"],["Email","Courriel","Correo electrónico"],["Signal sharing and alerts","Partage de signaux et alertes","Señales compartidas y alertas"],["No guaranteed profits or returns","Aucun profit ni rendement garanti","Sin beneficios ni rendimientos garantizados"],
["ABOUT NATHAUXFX","À PROPOS DE NATHAUXFX","ACERCA DE NATHAUXFX"],["Trading analysis and automation software","Logiciel d’analyse et d’automatisation du trading","Software de análisis y automatización de trading"],["What NathauxFX is — and what it is not","Ce qu’est NathauxFX — et ce qu’il n’est pas","Qué es NathauxFX — y qué no es"],["Software platform","Plateforme logicielle","Plataforma de software"],["Not a broker","Pas un courtier","No es un bróker"],["Your own broker account","Votre propre compte de courtage","Tu propia cuenta de corretaje"],["No guaranteed outcomes","Aucun résultat garanti","Sin resultados garantizados"],["How automation works","Fonctionnement de l’automatisation","Cómo funciona la automatización"],
["HOW IT WORKS","FONCTIONNEMENT","CÓMO FUNCIONA"],["From analysis to user-authorized execution","De l’analyse à l’exécution autorisée par l’utilisateur","Del análisis a la ejecución autorizada por el usuario"],["Market analysis","Analyse du marché","Análisis de mercado"],["Signals and risk controls","Signaux et contrôles du risque","Señales y controles de riesgo"],["Connect your own cTrader account","Connectez votre propre compte cTrader","Conecta tu propia cuenta de cTrader"],["Optional automated execution","Exécution automatisée facultative","Ejecución automatizada opcional"],["Email signal sharing","Partage de signaux par courriel","Compartir señales por correo"],["Important:","Important :","Importante:"],
["Last updated: September 4, 2026","Dernière mise à jour : 4 septembre 2026","Última actualización: 4 de septiembre de 2026"],["Trading risk","Risques du trading","Riesgo de trading"],["No guaranteed performance","Aucune performance garantie","Sin rendimiento garantizado"],["Software, not brokerage custody","Un logiciel, sans garde de courtage","Software, no custodia de corretaje"],["Automated trading","Trading automatisé","Trading automatizado"],["Third-party services","Services tiers","Servicios de terceros"],["User responsibility","Responsabilité de l’utilisateur","Responsabilidad del usuario"],["Terms of Use","Conditions d’utilisation","Términos de uso"],
["1. Software service","1. Service logiciel","1. Servicio de software"],["2. No guarantee or individualized advice","2. Aucune garantie ni conseil personnalisé","2. Sin garantías ni asesoramiento personalizado"],["3. Brokerage connections","3. Connexions de courtage","3. Conexiones de corretaje"],["4. Acceptable use","4. Utilisation acceptable","4. Uso aceptable"],["5. Availability and third parties","5. Disponibilité et tiers","5. Disponibilidad y terceros"],["6. Risk","6. Risque","6. Riesgo"],["7. Changes","7. Modifications","7. Cambios"],["8. Contact","8. Contact","8. Contacto"],["Information used to provide the service","Informations utilisées pour fournir le service","Información utilizada para prestar el servicio"],["Brokerage connections","Connexions de courtage","Conexiones de corretaje"],["Email features","Fonctions de courriel","Funciones de correo electrónico"],["How information may be used","Utilisation possible des informations","Cómo puede utilizarse la información"],["Security","Sécurité","Seguridad"],["Your choices","Vos choix","Tus opciones"]
].forEach(x=>add(...x));

[["Forex and leveraged trading involve substantial risk of loss. Please review the","Le Forex et le trading à effet de levier comporte un risque important de perte. Consultez l’","El Forex y el trading apalancado implica un riesgo considerable de pérdida. Revisa la"],["before using trading or automation features.","avant d’utiliser les fonctions de trading ou d’automatisation.","antes de usar las funciones de trading o automatización."],["Questions about these terms can be sent to","Les questions concernant ces conditions peuvent être envoyées à","Las preguntas sobre estos términos pueden enviarse a"],["You can choose whether to use optional features such as brokerage connections, automation and email sharing. Questions or requests concerning your NathauxFX account or information can be sent to","Vous pouvez choisir d’utiliser ou non les connexions de courtage, l’automatisation et le partage par courriel. Les questions ou demandes concernant votre compte ou vos informations peuvent être envoyées à","Puedes decidir si utilizas conexiones de corretaje, automatización y correo. Las preguntas o solicitudes sobre tu cuenta o información pueden enviarse a"]].forEach(x=>add(...x));

const P=[
["NathauxFX is trading analysis and automation software for EURUSD and Gold. It combines market structure, technical signals, fundamental insights, risk controls, Trader execution through your own connected broker account, and email signal sharing.","NathauxFX est un logiciel d’analyse et d’automatisation du trading pour l’EURUSD et l’or. Il combine la structure du marché, les signaux techniques, l’analyse fondamentale, les contrôles du risque, l’exécution via votre propre compte de courtage connecté et le partage de signaux par courriel.","NathauxFX es un software de análisis y automatización de trading para EURUSD y oro. Combina estructura de mercado, señales técnicas, información fundamental, controles de riesgo, ejecución mediante tu propia cuenta de corretaje conectada y señales compartidas por correo."],
["NathauxFX is trading analysis and automation software for EURUSD and Gold. It combines market structure, technical signals, fundamental insights, risk controls, cTrader execution through your own connected broker account, and email signal sharing.","NathauxFX est un logiciel d’analyse et d’automatisation du trading pour l’EURUSD et l’or. Il combine la structure du marché, les signaux techniques, l’analyse fondamentale, les contrôles du risque, l’exécution cTrader via votre propre compte connecté et le partage de signaux par courriel.","NathauxFX es un software de análisis y automatización de trading para EURUSD y oro. Combina estructura de mercado, señales técnicas, información fundamental, controles de riesgo, ejecución en cTrader mediante tu propia cuenta conectada y señales compartidas por correo."],
["NathauxFX is an independent software platform for market analysis, signals, risk management and optional trade automation. NathauxFX does not act as a broker and does not accept trading deposits or hold brokerage funds.","NathauxFX est une plateforme logicielle indépendante d’analyse des marchés, de signaux, de gestion du risque et d’automatisation facultative. NathauxFX n’agit pas comme courtier, n’accepte aucun dépôt de trading et ne conserve aucun fonds de courtage.","NathauxFX es una plataforma independiente para análisis de mercado, señales, gestión de riesgo y automatización opcional. No actúa como bróker, no acepta depósitos ni mantiene fondos de corretaje."],
["When automation is enabled, orders are sent to the user's own connected cTrader brokerage account under the permissions the user authorizes. Trading decisions, broker selection and account funding remain under the user's control.","Lorsque l’automatisation est activée, les ordres sont envoyés au propre compte cTrader connecté de l’utilisateur selon les autorisations accordées. Les décisions, le choix du courtier et le financement restent sous son contrôle.","Cuando se activa la automatización, las órdenes se envían a la cuenta cTrader conectada del usuario según los permisos autorizados. Las decisiones, la elección del bróker y la financiación permanecen bajo su control."],
["Risk disclosure: Forex and leveraged trading can result in substantial losses. NathauxFX provides software tools and information; it does not guarantee performance, returns or successful trades.","Avis de risque : le Forex et le trading à effet de levier peuvent entraîner des pertes importantes. NathauxFX fournit des outils et de l’information; il ne garantit ni performance, ni rendement, ni transaction réussie.","Divulgación de riesgos: el Forex y el trading apalancado pueden causar pérdidas importantes. NathauxFX ofrece herramientas e información; no garantiza rendimiento, rentabilidad ni operaciones exitosas."],
["NathauxFX is an independent software platform designed to help traders analyze EURUSD and Gold, organize trading decisions, apply risk controls, receive alerts, share signals by email, and optionally automate user-authorized trade execution through cTrader.","NathauxFX est une plateforme indépendante conçue pour aider les traders à analyser l’EURUSD et l’or, organiser leurs décisions, appliquer des contrôles du risque, recevoir des alertes, partager des signaux par courriel et automatiser facultativement l’exécution autorisée via cTrader.","NathauxFX es una plataforma independiente diseñada para ayudar a analizar EURUSD y oro, organizar decisiones, aplicar controles de riesgo, recibir alertas, compartir señales por correo y automatizar opcionalmente la ejecución autorizada mediante cTrader."],
["Market structure, technical signals, fundamental insights, risk tools, alerts and automation features.","Structure du marché, signaux techniques, analyse fondamentale, outils de risque, alertes et fonctions d’automatisation.","Estructura de mercado, señales técnicas, información fundamental, herramientas de riesgo, alertas y automatización."],
["NathauxFX does not provide brokerage custody and does not accept trading deposits.","NathauxFX ne fournit pas de garde de courtage et n’accepte pas de dépôts de trading.","NathauxFX no ofrece custodia de corretaje ni acepta depósitos de trading."],
["Connected trading accounts remain with the user's chosen brokerage provider.","Les comptes connectés restent auprès du courtier choisi par l’utilisateur.","Las cuentas conectadas permanecen con el bróker elegido por el usuario."],
["Trading involves risk. NathauxFX does not promise profits, returns, win rates or successful trades.","Le trading comporte des risques. NathauxFX ne promet ni profits, ni rendements, ni taux de réussite, ni transactions réussies.","El trading implica riesgo. NathauxFX no promete beneficios, rendimientos, tasas de acierto ni operaciones exitosas."],
["NathauxFX provides software tools and market information. Nothing on the platform is a guarantee of financial performance.","NathauxFX fournit des outils logiciels et des informations de marché. Rien sur la plateforme ne garantit une performance financière.","NathauxFX proporciona herramientas e información de mercado. Nada en la plataforma garantiza resultados financieros."],
["NathauxFX evaluates market structure, technical conditions and fundamental information for supported markets such as EURUSD and Gold.","NathauxFX évalue la structure du marché, les conditions techniques et les données fondamentales des marchés pris en charge comme l’EURUSD et l’or.","NathauxFX evalúa la estructura, las condiciones técnicas y la información fundamental de mercados compatibles como EURUSD y oro."],
["Trading involves risk. Signals and automation do not guarantee profits, win rates or successful trades.","Le trading comporte des risques. Les signaux et l’automatisation ne garantissent ni profits, ni taux de réussite, ni transactions réussies.","El trading implica riesgo. Las señales y la automatización no garantizan beneficios, tasas de acierto ni operaciones exitosas."],
["Forex, gold and other leveraged financial products can move rapidly and may result in substantial losses. You can lose some or all of the capital committed to trading.","Le Forex, l’or et d’autres produits à effet de levier peuvent évoluer rapidement et entraîner des pertes importantes. Vous pouvez perdre une partie ou la totalité du capital engagé.","El Forex, el oro y otros productos apalancados pueden moverse rápidamente y causar pérdidas importantes. Puedes perder parte o todo el capital destinado al trading."],
["Use only capital you can afford to lose and consider your own financial circumstances, experience and risk tolerance. If you need individualized financial or investment advice, consult an appropriately qualified professional.","N’utilisez que du capital que vous pouvez vous permettre de perdre et tenez compte de votre situation, de votre expérience et de votre tolérance au risque. Pour des conseils personnalisés, consultez un professionnel qualifié.","Utiliza solo capital que puedas permitirte perder y considera tu situación, experiencia y tolerancia al riesgo. Si necesitas asesoramiento personalizado, consulta a un profesional cualificado."]
];P.forEach(x=>add(...x));

[
["The platform can surface trading setups, entry context, stop-loss and target information, while applying configured risk rules and trading limits.","La plateforme peut présenter des configurations, le contexte d’entrée, le stop-loss et les objectifs, tout en appliquant les règles et limites de risque configurées.","La plataforma puede mostrar configuraciones, contexto de entrada, stop-loss y objetivos, aplicando las reglas y límites de riesgo configurados."],
["Users can authorize a supported cTrader brokerage account. NathauxFX does not take custody of brokerage funds; the connected account remains with the user's broker.","Les utilisateurs peuvent autoriser un compte cTrader pris en charge. NathauxFX ne garde aucun fonds; le compte reste auprès du courtier de l’utilisateur.","Los usuarios pueden autorizar una cuenta cTrader compatible. NathauxFX no custodia fondos; la cuenta permanece con el bróker del usuario."],
["If the user enables automation, NathauxFX can send orders to the connected account according to configured platform rules. The user can disable automation.","Si l’utilisateur active l’automatisation, NathauxFX peut envoyer des ordres au compte connecté selon les règles configurées. L’utilisateur peut la désactiver.","Si el usuario activa la automatización, NathauxFX puede enviar órdenes a la cuenta conectada según las reglas configuradas. El usuario puede desactivarla."],
["Signals and trading information can be shared or delivered by email when the relevant feature is used.","Les signaux et informations de trading peuvent être partagés ou envoyés par courriel lorsque cette fonction est utilisée.","Las señales y la información de trading pueden compartirse o enviarse por correo cuando se utiliza esa función."],
["NathauxFX provides trading analysis, signals, alerts, risk-management tools, email signal sharing and optional integrations that can support user-authorized automated execution. NathauxFX is not presented as a broker and does not accept trading deposits or hold brokerage funds.","NathauxFX fournit des analyses, signaux, alertes, outils de gestion du risque, partage par courriel et intégrations facultatives permettant une exécution automatisée autorisée. NathauxFX n’est pas un courtier, n’accepte aucun dépôt et ne conserve aucun fonds de courtage.","NathauxFX ofrece análisis, señales, alertas, herramientas de riesgo, envío por correo e integraciones opcionales para ejecución automatizada autorizada. No es un bróker, no acepta depósitos ni mantiene fondos de corretaje."],
["Trading information and software features are provided for informational and tool-based use. NathauxFX does not guarantee profits, returns, win rates or successful trades. Users remain responsible for their trading decisions and risk.","Les informations et fonctions sont fournies à titre informatif et comme outils. NathauxFX ne garantit ni profits, ni rendements, ni taux de réussite, ni transactions réussies. Les utilisateurs restent responsables de leurs décisions et de leurs risques.","La información y las funciones se ofrecen con fines informativos y como herramientas. NathauxFX no garantiza beneficios, rendimientos, tasas de acierto ni operaciones exitosas. Los usuarios siguen siendo responsables de sus decisiones y riesgos."],
["If you connect a third-party brokerage or cTrader account, you authorize the platform to use the permissions required for the features you choose. Your brokerage relationship remains between you and your broker. You are responsible for monitoring the account and disabling automation when desired.","Si vous connectez un compte de courtage tiers ou cTrader, vous autorisez la plateforme à utiliser les permissions nécessaires aux fonctions choisies. Votre relation de courtage reste entre vous et votre courtier. Vous devez surveiller le compte et désactiver l’automatisation lorsque souhaité.","Si conectas una cuenta de corretaje externa o cTrader, autorizas a la plataforma a usar los permisos necesarios para las funciones elegidas. La relación de corretaje sigue siendo entre tú y tu bróker. Eres responsable de supervisar la cuenta y desactivar la automatización cuando quieras."],
["You agree not to misuse the service, attempt unauthorized access, interfere with platform operation, or use the service in a way that violates applicable law or third-party rights.","Vous acceptez de ne pas utiliser abusivement le service, tenter un accès non autorisé, perturber son fonctionnement ou l’utiliser en violation de la loi ou des droits de tiers.","Aceptas no utilizar indebidamente el servicio, intentar accesos no autorizados, interferir con su funcionamiento ni usarlo contra la ley o los derechos de terceros."],
["Market data, brokerage connectivity, email delivery and other third-party services may experience delays, outages or errors. NathauxFX cannot control third-party execution, spreads, pricing, fees or service availability.","Les données de marché, connexions de courtage, livraisons de courriels et autres services tiers peuvent subir des retards, pannes ou erreurs. NathauxFX ne contrôle pas l’exécution, les écarts, les prix, les frais ni la disponibilité des tiers.","Los datos de mercado, conexiones de corretaje, correos y otros servicios externos pueden sufrir retrasos, interrupciones o errores. NathauxFX no controla la ejecución, diferenciales, precios, comisiones ni disponibilidad de terceros."],
["Forex and leveraged trading involve substantial risk of loss. Please review the Risk Disclosure before using trading or automation features.","Le Forex et le trading à effet de levier comportent un risque important de perte. Consultez l’Avis de risque avant d’utiliser les fonctions de trading ou d’automatisation.","El Forex y el trading apalancado implican un riesgo considerable de pérdida. Revisa la Divulgación de riesgos antes de usar las funciones de trading o automatización."],
["Features and these terms may be updated as the service evolves. The current version is published on this page.","Les fonctions et ces conditions peuvent être mises à jour à mesure que le service évolue. La version actuelle est publiée sur cette page.","Las funciones y estos términos pueden actualizarse a medida que evoluciona el servicio. La versión vigente se publica en esta página."],
["Questions about these terms can be sent to renathauxfx@outlook.com.","Les questions concernant ces conditions peuvent être envoyées à renathauxfx@outlook.com.","Las preguntas sobre estos términos pueden enviarse a renathauxfx@outlook.com."],
["Depending on the features you use, NathauxFX may process information such as account details, authentication information, platform settings, trading preferences, connected brokerage identifiers, signal-sharing information, technical logs and device or browser information needed to operate and secure the service.","Selon les fonctions utilisées, NathauxFX peut traiter les détails du compte, informations d’authentification, réglages, préférences de trading, identifiants de courtage connectés, informations de partage de signaux, journaux techniques et données d’appareil ou de navigateur nécessaires au fonctionnement sécurisé du service.","Según las funciones utilizadas, NathauxFX puede procesar datos de cuenta, autenticación, configuración, preferencias de trading, identificadores de corretaje conectados, información de señales, registros técnicos y datos del dispositivo o navegador necesarios para operar y proteger el servicio."],
["When you connect a supported brokerage or cTrader account, the platform may process the identifiers, permissions and trading information required to provide the connected features. NathauxFX does not require you to transfer brokerage funds to NathauxFX in order to use a broker connection.","Lorsque vous connectez un compte de courtage ou cTrader pris en charge, la plateforme peut traiter les identifiants, permissions et informations de trading nécessaires. NathauxFX ne vous demande pas de lui transférer des fonds pour utiliser une connexion de courtage.","Cuando conectas una cuenta de corretaje o cTrader compatible, la plataforma puede procesar los identificadores, permisos e información necesarios. NathauxFX no exige transferirle fondos para usar una conexión de corretaje."],
["If you use email alerts or signal sharing, email addresses and the content required to deliver those messages may be processed for that purpose.","Si vous utilisez les alertes ou le partage par courriel, les adresses et le contenu nécessaires à la livraison de ces messages peuvent être traités à cette fin.","Si utilizas alertas o señales por correo, las direcciones y el contenido necesario para entregar esos mensajes pueden procesarse con ese fin."],
["Information may be used to operate accounts, provide requested features, maintain platform security, troubleshoot errors, improve reliability, communicate service information and comply with applicable obligations.","Les informations peuvent servir à exploiter les comptes, fournir les fonctions demandées, maintenir la sécurité, résoudre les erreurs, améliorer la fiabilité, communiquer au sujet du service et respecter les obligations applicables.","La información puede utilizarse para operar cuentas, prestar funciones, mantener la seguridad, resolver errores, mejorar la fiabilidad, comunicar información del servicio y cumplir obligaciones aplicables."],
["Features may depend on third-party providers such as hosting, email delivery, market-data services, cTrader or brokerage services. Those providers may process information under their own terms and privacy practices.","Les fonctions peuvent dépendre de fournisseurs tiers comme l’hébergement, la livraison de courriels, les données de marché, cTrader ou les services de courtage. Ces fournisseurs peuvent traiter des informations selon leurs propres conditions et pratiques.","Las funciones pueden depender de proveedores externos de alojamiento, correo, datos de mercado, cTrader o corretaje. Estos proveedores pueden procesar información según sus propios términos y prácticas."],
["NathauxFX uses technical and operational measures intended to protect platform information. No internet service can guarantee absolute security, so users should protect their own devices, credentials and brokerage accounts.","NathauxFX utilise des mesures techniques et opérationnelles visant à protéger les informations. Aucun service Internet ne peut garantir une sécurité absolue; les utilisateurs doivent protéger leurs appareils, identifiants et comptes de courtage.","NathauxFX utiliza medidas técnicas y operativas para proteger la información. Ningún servicio de Internet garantiza seguridad absoluta; los usuarios deben proteger sus dispositivos, credenciales y cuentas de corretaje."],
["You can choose whether to use optional features such as brokerage connections, automation and email sharing. Questions or requests concerning your NathauxFX account or information can be sent to renathauxfx@outlook.com.","Vous pouvez choisir d’utiliser ou non les connexions de courtage, l’automatisation et le partage par courriel. Les questions ou demandes concernant votre compte ou vos informations peuvent être envoyées à renathauxfx@outlook.com.","Puedes decidir si utilizas conexiones de corretaje, automatización y correo. Las preguntas o solicitudes sobre tu cuenta o información pueden enviarse a renathauxfx@outlook.com."]
].forEach(x=>add(...x));

const originals=new WeakMap();
function apply(lang){lang=["fr","es"].includes(lang)?lang:"en";document.documentElement.lang=lang;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(!originals.has(n))originals.set(n,n.nodeValue);const raw=originals.get(n),key=raw.trim();if(!key)continue;const val=lang==="en"?key:(T[lang][key]||key);n.nodeValue=raw.replace(key,val);}document.querySelectorAll("#landingLang,[data-public-lang]").forEach(s=>s.value=lang.toUpperCase());try{localStorage.setItem(KEY,lang)}catch(e){}}
document.addEventListener("DOMContentLoaded",()=>{let lang="en";try{lang=localStorage.getItem(KEY)||navigator.language.slice(0,2)}catch(e){}document.querySelectorAll("#landingLang,[data-public-lang]").forEach(s=>s.addEventListener("change",()=>apply(s.value.toLowerCase())));apply(lang)});
})();
