const assert = require('node:assert/strict');
const { authorityDisplay, managementView, managementMarkup } = require('../live-authority-display.js');
const none = authorityDisplay({live_strategy_model:'V3B',signal:'SELL',live_strategy_display:{execution_source:'NONE',reason:'NO_LIVE_STRATEGY_FOR_SYMBOL'}});
assert.equal(none.signal, 'WAIT');
assert.equal(none.strategy_name, 'NO LIVE STRATEGY ASSIGNED');
assert.equal(none.conditions[0].state, 'BLOCKED');
assert.equal(authorityDisplay({live_strategy_model:'V3B',signal:'SELL'}).reason, 'LIVE_AUTHORITY_UNAVAILABLE');
assert.equal(authorityDisplay({execution_authority:{source:'V3B'}}), null);
const conditions=[{key:'custom',label:'Saved custom threshold',state:'ERROR',reason:'Evaluator unavailable'}];
const studio=authorityDisplay({live_strategy_display:{execution_authority:{source:'STRATEGY_STUDIO',strategy_name:'Gold 931 v18',strategy_id:'gold'},conditions,signal:'WAIT'}});
assert.deepEqual(studio.conditions,conditions);
assert.equal(studio.strategy_name,'Gold 931 v18');
assert.equal(studio.strategy_id,'gold');
const trade={source:'broker',profit_protected:true,protected_sl_price:3000,trade_management:{execution_source:'STRATEGY_STUDIO',strategy_name:'Original Gold',tp1_state:'HIT',protection_state:'PENDING',target_protected_sl:3000,broker_sl:2900}};
assert.equal(managementView(trade).confirmed,false);
assert.match(managementMarkup(trade),/Original Gold/);
assert.match(managementMarkup(trade),/PENDING/);
assert.doesNotMatch(managementMarkup(trade),/CONFIRMED/);
trade.trade_management.protection_state='FAILED';
assert.equal(managementView(trade).confirmed,false);
trade.trade_management.protection_state='CONFIRMED';
assert.equal(managementView(trade).confirmed,false,'status alone without broker readback cannot confirm');
trade.trade_management.broker_confirmed_sl=3000;
assert.equal(managementView(trade).confirmed,true);
trade.trade_management.tp1_state='PARTIAL_CLOSED';
assert.match(managementMarkup(trade),/PARTIAL CLOSED/);
assert.match(managementMarkup({source:'broker'}),/MANUAL \/ LEGACY POSITION/);
assert.doesNotMatch(managementMarkup({source:'broker'}),/Gold/);
assert.doesNotMatch(managementMarkup({trade_management:{strategy_name:'<script>',execution_source:'STRATEGY_STUDIO'}}),/<script>/);
console.log('Live authority and durable management display passed');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const frontend = path.join(__dirname,'..');
const mobileSource = fs.readFileSync(path.join(frontend,'mobileNav.js'),'utf8');
const render = mobileSource.slice(mobileSource.indexOf('  function renderIsch('),mobileSource.indexOf('  function ischDetail('));
let rendered='';
const context={cache:{},selectedSymbol:()=> 'EURUSD',window:{NathauxLiveAuthority:require('../live-authority-display.js'),NathauxMobileV3B:{mobileV3bFacts:()=>{throw Error('implicit V3B evaluation')}}},first:(...v)=>v.find(x=>x!=null&&x!==''),esc:String,row:(label,value)=>`${label}:${value}`,openDetail:(a,b,c)=>{rendered=b+c;}};
vm.createContext(context);vm.runInContext(render,context);
context.renderIsch({_meta:{live_strategy_display_by_symbol:{EURUSD:{execution_source:'NONE'}}},EURUSD:{signal:'SELL'}});
assert.match(rendered,/NO LIVE STRATEGY ASSIGNED/);
assert.match(rendered,/Auto entry:BLOCKED/);
assert.doesNotMatch(rendered,/BOS|V3B/);
context.renderIsch({EURUSD:{}});
assert.match(rendered,/LIVE STRATEGY UNAVAILABLE/);
context.renderIsch({_meta:{live_strategy_display_by_symbol:{EURUSD:{execution_source:'STRATEGY_STUDIO',strategy_name:'Test EUR',conditions,signal:'WAIT'}}}});
assert.match(rendered,/Saved custom threshold:ERROR/);
assert.match(rendered,/Evaluator unavailable/);
assert.doesNotMatch(rendered,/BOS|V3B/);
const dashboard=fs.readFileSync(path.join(frontend,'script.js'),'utf8');
vm.runInContext(dashboard.slice(dashboard.indexOf('function getVisibleSignal('),dashboard.indexOf('\nfunction ',dashboard.indexOf('function getVisibleSignal(')+10)),context);
assert.equal(context.getVisibleSignal({signal:'SELL',live_strategy_display:{execution_source:'NONE'}}),'WAIT');
assert.equal(context.getVisibleSignal({signal:'SELL'}),'WAIT');
assert.equal(context.getVisibleSignal({live_strategy_display:{execution_source:'STRATEGY_STUDIO',signal:'BUY'}}),'BUY');
console.log('Rendered mobile authority and dashboard signal precedence passed');
function element(){return {dataset:{},children:[],style:{setProperty(){},removeProperty(){}},classList:{add(){},toggle(){},contains(){return false;}},append(...nodes){this.children.push(...nodes);},replaceChildren(...nodes){this.children=nodes;},textContent:''};}
const grid=element();const summary=element();const details=element();details.querySelector=()=>summary;
global.document={getElementById:id=>id==='live-strategy-condition-grid'?grid:null,querySelector:q=>q==='details.entry-strategy-debug'?details:null,createElement:element};
const history=require('../history.js');
assert.equal(history.renderStudioPresentation({live_strategy_display:{execution_source:'NONE'}}),true);
assert.match(summary.textContent,/NO LIVE STRATEGY ASSIGNED/);
assert.ok(grid.children.some(x=>x.textContent==='BLOCKED'));
assert.equal(history.renderStudioPresentation({live_strategy_display:{execution_source:'STRATEGY_STUDIO',strategy_name:'Saved Gold',conditions}}),true);
assert.match(summary.textContent,/Saved Gold/);
assert.ok(grid.children.some(x=>x.textContent==='Saved custom threshold'));
assert.ok(grid.children.some(x=>x.textContent==='ERROR'));
assert.equal(grid.children.some(x=>/BOS|V3B/.test(x.textContent)),false);
delete global.document;
console.log('Rendered desktop dynamic condition and NONE authority passed');
